name: Golang CI
on:
  push:
    branches:
      - master
      - dev
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/golangci.yml"
  pull_request:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/golangci.yml"

permissions:
  contents: read
  pull-requests: read
  security-events: write

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.1.6

        golangci-lint migrate --format yml

     # - name: golangci-lint
       # uses: golangci/golangci-lint-action@1481404843c368bc19ca9406f87d6e0fc97bdcfd
        #with:
        #  version: latest
        #  only-new-issues: true